apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: mozart
  name: mozart
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  - name: "5555"
    port: 5555
    targetPort: 5555
  - name: "8888"
    port: 8888
    targetPort: 8888
  - name: "8898"
    port: 8898
    targetPort: 8898
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    io.kompose.service: mozart
status:
  loadBalancer: {}
