apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - args:
        - elasticsearch
        - -Des.node.name='grq-elasticsearch'
        - -Des.cluster.name='products_cluster'
        - -Des.bootstrap.mlockall=true
        - -Des.network.host=0
        - -Des.index.number_of_shards=16
        - -Des.script.engine.groovy.inline.aggs=on
        env:
        - name: ES_HEAP_SIZE
          value: m
        - name: MAX_LOCKED_MEMORY
          value: unlimited
        image: hysds/elasticsearch
        name: grq-elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config
          name: elasticsearch-claim0
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-claim1
      restartPolicy: Always
      volumes:
      - name: elasticsearch-claim0
        persistentVolumeClaim:
          claimName: elasticsearch-claim0
      - name: elasticsearch-claim1
        persistentVolumeClaim:
          claimName: elasticsearch-claim1
status: {}
