apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: metrics
  name: metrics
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: metrics
    spec:
      containers:
      - image: hysds/metrics
        name: metrics
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /sys/fs/cgroup
          name: metrics-claim0
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: metrics-claim1
        - mountPath: /home/ops/mozart/etc
          name: metrics-claim2
        - mountPath: /home/ops/mozart/log
          name: metrics-claim3
        - mountPath: /home/ops/.aws
          name: metrics-claim4
        - mountPath: /home/ops/.boto
          name: metrics-claim5
        - mountPath: /home/ops/.s3cfg
          name: metrics-claim6
        - mountPath: /home/ops/.netrc
          name: metrics-claim7
      restartPolicy: Always
      volumes:
      - name: metrics-claim0
        persistentVolumeClaim:
          claimName: metrics-claim0
          readOnly: true
      - name: metrics-claim1
        persistentVolumeClaim:
          claimName: metrics-claim1
      - name: metrics-claim2
        persistentVolumeClaim:
          claimName: metrics-claim2
      - name: metrics-claim3
        persistentVolumeClaim:
          claimName: metrics-claim3
      - name: metrics-claim4
        persistentVolumeClaim:
          claimName: metrics-claim4
      - name: metrics-claim5
        persistentVolumeClaim:
          claimName: metrics-claim5
      - name: metrics-claim6
        persistentVolumeClaim:
          claimName: metrics-claim6
      - name: metrics-claim7
        persistentVolumeClaim:
          claimName: metrics-claim7
status: {}
