apiVersion: v1
kind: Pod
metadata:
  name: mozart-es
spec:
  containers:
  - name: mozart-es
    image: hysds/elasticsearch:1.7
    command: ["elasticsearch"]
    args: ["-Des.node.name='mozart-es'",
           "-Des.cluster.name='resource_cluster'",
           "-Des.bootstrap.mlockall=true",
           "-Des.network.host=0" ]
    ports:
    - containerPort: 9200
      name: http
    - containerPort: 9300
      name: tcp
    resources:
      limits:
        cpu: "0.1"
    env:
    - name: ES_HEAP_SIZE
      value: "100m"
    - name: MAX_LOCKED_MEMORY
      value: "unlimited"
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: data
    - mountPath: /usr/share/elasticsearch/config
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      emptyDir: {}
