apiVersion: v1
kind: Pod
metadata:
  name: mozart-rabbitmq
spec:
  containers:
  - name: mozart-rabbitmq
    image: hysds/rabbitmq:latest
    ports:
    - containerPort: 5672
      name: amqp
    - containerPort: 15672
      name: http
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /var/lib/rabbitmq
      name: data
    - mountPath: /etc/rabbitmq/rabbitmq.config
      name: config
      subPath: rabbitmq-config
    - mountPath: /etc/default/rabbitmq-server
      name: config
      subPath: rabbitmq-server
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: mozart-rabbitmq-config
