apiVersion: v1
kind: Pod
metadata:
  name: mozart-redis
spec:
  containers:
  - name: mozart-redis
    image: hysds/redis:latest
    command: [ "redis-server" ]
    args: [ "/redis-master/redis.conf" ]
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /data/redis
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: mozart-redis-config
        items:
        - key: redis-config
          path: redis.conf
