apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grq-elasticsearch-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
  labels:
    component: grq
    run: grq-elasticsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
