apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grq-elasticsearch-pvc
  labels:
    component: grq
    run: grq-elasticsearch-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      component: grq
      run: grq-elasticsearch-pv
