apiVersion: v1
kind: Pod
metadata:
  name: grq
spec:
  containers:
  - name: grq
    image: hysds/grq:latest
    ports:
    - containerPort: 80
      name: http
    - containerPort: 443
      name: https
    - containerPort: 8878
      name: grq2
    - containerPort: 8879
      name: tosca
    - containerPort: 9001
      name: supervisord
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /home/ops/sciflo/etc/celeryconfig.py
      name: global-config
      subPath: celeryconfig.py
    - mountPath: /home/ops/mozart/etc/datasets.json
      name: global-config
      subPath: datasets.json
    - mountPath: /home/ops/sciflo/etc/grq2_settings.cfg
      name: config
      subPath: settings.cfg.grq2
    - mountPath: /home/ops/sciflo/etc/tosca_settings.cfg
      name: config
      subPath: settings.cfg.tosca
    - mountPath: /home/ops/sciflo/etc/supervisord.conf
      name: config
      subPath: supervisord.conf
    - mountPath: /home/ops/sciflo/log
      name: log
  volumes:
  - name: global-config
    configMap:
      name: hysds-global-config
  - name: config
    configMap:
      name: hysds-grq-config
  - name: log
    emptyDir: {}
