apiVersion: v1
kind: Service
metadata:
  name: factotum
  labels:
    component: factotum
    run: factotum
spec:
  type: NodePort
  ports:
  - port: 22
    protocol: TCP
    name: ssh
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  - port: 8085
    protocol: TCP
    name: dav
  - port: 9001
    protocol: TCP
    name: supervisord
  selector:
    component: factotum
    run: factotum
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factotum
  labels:
    component: factotum
    run: factotum
spec:
  selector:
    matchLabels:
      component: factotum
      run: factotum
  replicas: 1
  template:
    metadata:
      labels:
        component: factotum
        run: factotum
    spec:
      containers:
      - name: factotum
        image: hysds/verdi:latest
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 8085
          name: dav
        - containerPort: 9001
          name: supervisord
        resources:
          limits:
            cpu: "0.5"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
        - mountPath: /home/ops/.ssh/id_rsa
          name: global-secrets
          subPath: id_rsa
          readOnly: true
        - mountPath: /home/ops/.ssh/authorized_keys
          name: global-secrets
          subPath: id_rsa.pub
          readOnly: true
        - mountPath: /home/ops/verdi/etc/celeryconfig.py
          name: global-config
          subPath: celeryconfig.py
        - mountPath: /home/ops/verdi/etc/datasets.json
          name: global-config
          subPath: datasets.json
        - mountPath: /home/ops/verdi/etc/conf.d/factotum.conf
          name: config
          subPath: factotum.conf
        - mountPath: /home/ops/verdi/log
          name: log
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: global-secrets
        secret:
          secretName: hysds-global-secrets
      - name: global-config
        configMap:
          name: hysds-global-config
      - name: config
        configMap:
          name: hysds-factotum-config
      - name: log
        emptyDir: {}
