apiVersion: v1
kind: Service
metadata:
  name: metrics
  labels:
    component: metrics
    run: metrics
spec:
  type: NodePort
  ports:
  - port: 22
    protocol: TCP
    name: ssh
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  - port: 5601
    protocol: TCP
    name: kibana
  - port: 9200
    protocol: TCP
    name: es-api
  - port: 9300
    protocol: TCP
    name: es-data
  - port: 9001
    protocol: TCP
    name: supervisord
  selector:
    component: metrics
    run: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  labels:
    component: metrics
    run: metrics
spec:
  selector:
    matchLabels:
      component: metrics
      run: metrics
  replicas: 1
  template:
    metadata:
      labels:
        component: metrics
        run: metrics
    spec:
      containers:
      - name: metrics
        image: hysds/metrics:latest
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 5601
          name: kibana
        - containerPort: 9200
          name: es-api
        - containerPort: 9300
          name: es-data
        - containerPort: 9001
          name: supervisord
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /home/ops/.ssh/id_rsa
          name: global-secrets
          subPath: id_rsa
          readOnly: true
        - mountPath: /home/ops/.ssh/authorized_keys
          name: global-secrets
          subPath: id_rsa.pub
          readOnly: true
        - mountPath: /home/ops/sciflo/etc/celeryconfig.py
          name: global-config
          subPath: celeryconfig.py
        - mountPath: /home/ops/mozart/etc/datasets.json
          name: global-config
          subPath: datasets.json
        - mountPath: /home/ops/metrics/etc/indexer.conf
          name: config
          subPath: indexer.conf
        - mountPath: /home/ops/sciflo/etc/supervisord.conf
          name: config
          subPath: supervisord.conf
        - mountPath: /home/ops/sciflo/log
          name: log
      volumes:
      - name: global-secrets
        secret:
          secretName: hysds-global-secrets
      - name: global-config
        configMap:
          name: hysds-global-config
      - name: config
        configMap:
          name: hysds-metrics-config
      - name: log
        emptyDir: {}
