apiVersion: v1
kind: Pod
metadata:
  name: metrics
spec:
  containers:
  - name: metrics
    image: hysds/metrics:latest
    ports:
    - containerPort: 80
      name: http
    - containerPort: 443
      name: https
    - containerPort: 5601
      name: kibana
    - containerPort: 9200
      name: es-api
    - containerPort: 9300
      name: es-data
    - containerPort: 9001
      name: supervisord
    resources:
      limits:
        cpu: "0.5"
    volumeMounts:
    - mountPath: /home/ops/metrics/etc/celeryconfig.py
      name: global-config
      subPath: celeryconfig.py
    - mountPath: /home/ops/metrics/etc/datasets.json
      name: global-config
      subPath: datasets.json
    - mountPath: /home/ops/metrics/etc/indexer.conf
      name: config
      subPath: indexer.conf
    - mountPath: /home/ops/metrics/etc/supervisord.conf
      name: config
      subPath: supervisord.conf
    - mountPath: /home/ops/metrics/log
      name: log
  volumes:
  - name: global-config
    configMap:
      name: hysds-global-config
  - name: config
    configMap:
      name: hysds-metrics-config
  - name: log
    emptyDir: {}
